Repository engsal-bin/FlickClick, pull requests merged in 2025-02, with the labels that each got.

#12 9 feat 장르 페이지
  src/api/axios.ts
  src/components/genresPage/GenreList.tsx
  src/components/genresPage/MediaList.tsx
  src/components/genresPage/OttIcons.tsx
  src/components/genresPage/TimesList.tsx
  src/components/genresPage/ToggleList.tsx
  src/components/genresPage/YearsList.tsx
  src/pages/Genres.tsx
Labels: ✨ Feat

#14 13 fix 헤더 및 모바일 사이드바
  src/assets/icon/translate_lang.svg
  src/components/common/MainThumbnail.tsx
  src/components/genresPage/TimesList.tsx
  src/components/genresPage/ToggleList.tsx
  src/components/notification/SideToggleList.tsx
  src/components/rootlayouts/Header.tsx
  src/components/rootlayouts/Notification.tsx
Labels: 🔧 Fix

#17 api 함수 생성 및 영화 예고편 컴포넌트
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/common.ts
  src/api/index.ts
  src/api/movie.ts
  src/api/search.ts
  src/api/tv.ts
  src/api/user.ts
  src/components/common/Contents.tsx
  src/components/common/Trailer.tsx
  src/components/common/TrailerModal.tsx
  src/components/common/Trailers.tsx
  src/components/rootlayouts/Header.tsx
  src/components/rootlayouts/Notification.tsx
  src/components/upcoming/UpcomingCredits.tsx
  src/components/upcoming/UpcomingOverview.tsx
  src/components/upcoming/UpcomingVideo.tsx
  src/pages/DetailSeries.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Movies.tsx
  src/pages/NewUpdate.tsx
  src/pages/Popular.tsx
  src/pages/Series.tsx
  src/pages/Upcoming.tsx
  src/type/type.d.ts
Labels: ✨ Feat

#22 21 feat 상세페이지
  package.json
  src/components/common/DetailIntroBox.tsx
  src/components/common/SeasonBox.tsx
  src/components/common/Tag.tsx
  src/pages/DetailSeries.tsx
  src/type/type.d.ts
Labels: ✨ Feat, 🔧 Fix

#24 23 feat 시즌 상세 페이지
  src/App.tsx
  src/api/tv.ts
  src/components/common/DetailIntroBox.tsx
  src/components/common/Episodes.tsx
  src/components/common/MainThumbnail.tsx
  src/components/common/PersonList.tsx
  src/components/common/SeasonBox.tsx
  src/pages/DetailSeason.tsx
  src/pages/DetailSeries.tsx
  src/type/type.d.ts
Labels: 🔧 Fix

#26 fix: 에피소드 상세 페이지
  src/App.tsx
  src/components/common/DetailEpisodeIntroBox.tsx
  src/components/common/DetailIntroBox.tsx
  src/components/common/Episodes.tsx
  src/components/common/PersonList.tsx
  src/components/common/Tag.tsx
  src/pages/DetailEpisode.tsx
  src/pages/DetailSeason.tsx
Labels: 🔧 Fix

#28 ✨ feat 공개 예정 더보기 페이지
  src/App.tsx
  src/api/common.ts
  src/api/movie.ts
  src/api/search.ts
  src/assets/logo/socialLogo/logo.svg
  src/components/OttIcon.tsx
  src/components/common/Contents.tsx
  src/components/common/Trailers.tsx
  src/components/upcoming/Upcoming.tsx
  src/components/upcoming/UpcomingCredits.tsx
  src/components/upcoming/UpcomingCreditsDetail.tsx
  src/components/upcoming/UpcomingGenre.tsx
  src/components/upcoming/UpcomingGenres.tsx
  src/components/upcoming/UpcomingInfo.tsx
  src/components/upcoming/UpcomingOtt.tsx
  src/components/upcoming/UpcomingOverview.tsx
  src/components/upcoming/UpcomingTitle.tsx
  src/components/upcoming/UpcomingVideo.tsx
  src/pages/Main.tsx
  src/pages/Popular.tsx
  src/pages/Upcoming.tsx
  src/pages/Upcomings.tsx
  src/type/type.d.ts
  tailwind.config.js
Labels: ✨ Feat

#29 27 feat 시리즈 상세페이지 시즌 무
  src/components/common/ArgorithmIP.tsx
  src/components/common/DetailEpisodeIntroBox.tsx
  src/components/common/DetailIntroBox.tsx
  src/components/common/MainThumbnail.tsx
  src/components/common/PersonList.tsx
  src/components/common/SeasonBox.tsx
  src/pages/DetailEpisode.tsx
Labels: 🔧 Fix

#33 ✨ feat 인기 급상승 페이지
  src/components/common/Contents.tsx
  src/components/common/ContentsWithoutViewMore.tsx
  src/pages/Popular.tsx
  src/type/type.d.ts
Labels: ✨ Feat

#39 ✨ 신규 업데이트 페이지
  src/components/common/GenreTag.tsx
  src/pages/NewUpdate.tsx
  src/type/type.d.ts
Labels: ✨ Feat

#40 [FEAT] 검색 기능 구현
  src/api/search.ts
  src/components/rootlayouts/Header.tsx
  src/components/rootlayouts/Searchbar.tsx
  src/css/tallwind.css
  src/hooks/useDebounce.ts
Labels: ✨ Feat

#41 [DELETE] 병합 오류 난 코드 수정
  src/components/rootlayouts/Header.tsx
Labels: 🔧 Fix

#44 [FEAT] 검색 기능 추가 구현
  src/components/rootlayouts/Header.tsx
  src/components/rootlayouts/Searchbar.tsx
Labels: ✨ Feat

#47 🚨 공개 예정 페이지 더보기 버튼 수정
  src/components/upcoming/UpcomingOverview.tsx
Labels: 🔧 Fix
