Repository engsal-bin/FlickClick, pull requests merged in 2025-03, with the labels that each got.

#49 Feat: 댓글, 토론 기능 구현
  src/api/common.ts
  src/api/movie.ts
  src/assets/icon/sendBlue.svg
  src/components/common/Argument.tsx
  src/components/common/ArgumentReview.tsx
  src/components/common/Arguments.tsx
  src/components/common/InputTextarea.tsx
  src/components/common/Review.tsx
  src/components/common/Reviews.tsx
  src/pages/DetailEpisode.tsx
  src/pages/DetailMovie.tsx
  src/pages/DetailSeason.tsx
  src/pages/DetailSeriesNoSeason.tsx
  src/type/type.d.ts
Labels: ✨ Feat

#51 Fix 메인썸네일상세페이지 #43
  package.json
  src/App.tsx
  src/api/movie.ts
  src/api/tv.ts
  src/assets/icon/imagenone.svg
  src/assets/icon/imagenone2.svg
  src/components/common/DetailIntroBox.tsx
  src/components/common/Episodes.tsx
  src/components/common/MainThumbnail.tsx
  src/components/common/PersonList.tsx
  src/pages/DetailMovie.tsx
  src/pages/DetailSeason.tsx
  src/pages/DetailSeries.tsx
  src/type/type.d.ts
Labels: ✨ Feat, 🔧 Fix

#55 fix/feat: 원형토글 추가 및 타입 및 변수명 변경
  src/components/common/MainThumbnail.tsx
  src/type/type.d.ts
Labels: ✨ Feat, 🔧 Fix

#57 Feat 상세페이지작품추천 #56
  src/api/movie.ts
  src/api/tv.ts
  src/components/common/ArgorithmIP.tsx
  src/components/common/DetailEpisodeIntroBox.tsx
  src/components/common/DetailIntroBox.tsx
  src/pages/DetailEpisode.tsx
  src/pages/DetailMovie.tsx
  src/pages/DetailSeason.tsx
  src/pages/DetailSeries.tsx
  src/type/type.d.ts
Labels: ✨ Feat, 🔧 Fix

#59 Feat: 토론, 댓글 기능 구현
  src/api/common.ts
  src/components/common/Argument.tsx
  src/components/common/ArgumentReview.tsx
  src/components/common/Arguments.tsx
  src/components/common/InputTextarea.tsx
  src/components/common/Review.tsx
  src/components/common/Reviews.tsx
  src/pages/DetailEpisode.tsx
  src/pages/DetailMovie.tsx
  src/pages/DetailSeason.tsx
  src/type/type.d.ts
Labels: ✨ Feat

#61 Feat: 댓글과 토론의 기능 추가 및 스타일 변경
  src/api/common.ts
  src/components/common/Argument.tsx
  src/components/common/ArgumentReview.tsx
  src/components/common/Arguments.tsx
  src/components/common/InputTextarea.tsx
  src/components/common/Review.tsx
  src/components/common/Reviews.tsx
  src/type/type.d.ts
Labels: 🎨 Design, ✨ Feat, 🔨 Refactor

#63 Feat 마이페이지 스크랩구현 #58
  src/api/mypageInfo.ts
  src/assets/icon/noScrapIcon.svg
  src/components/common/DetailEpisodeIntroBox.tsx
  src/components/common/DetailIntroBox.tsx
  src/components/common/PersonList.tsx
  src/components/common/SeasonBox.tsx
  src/components/mypage/EpisodeContent.tsx
  src/components/mypage/ScrapContent.tsx
  src/components/mypage/ScrapEpisode.tsx
  src/components/mypage/ScrapMovie.tsx
  src/components/mypage/ScrapSeason.tsx
  src/pages/DetailSeries.tsx
  src/pages/Mypage.tsx
Labels: ✨ Feat, 🔧 Fix

#65 Featbug 디테일인트로박스오류해결 및 스켈레톤 #64
  src/components/common/DetailEpisodeIntroBox.tsx
  src/components/common/DetailIntroBox.tsx
  src/components/common/MainThumbnail.tsx
Labels: 🐛 Bug, ✨ Feat

#67 Bug 메인썸네일 원형토글 동작오류 #66
  index.html
  public/favicon.png
  src/components/common/MainThumbnail.tsx
  src/components/common/Review.tsx
  src/components/common/SeasonBox.tsx
Labels: 🐛 Bug

#69 Feat 컨텐츠 변경 이동 시 화면 최상단으로 렌더링 #68
  src/App.tsx
  src/components/common/MainThumbnail.tsx
  src/pages/DetailEpisode.tsx
  src/pages/DetailMovie.tsx
  src/pages/DetailSeason.tsx
  src/pages/DetailSeries.tsx
  src/pages/DetailSeriesNoSeason.tsx
Labels: 🐛 Bug, ✨ Feat

#73 bug: 원형토글오류 해결 및 모바일 디바이스 간격 오류 해결
  package.json
  src/components/common/MainThumbnail.tsx
  src/css/index.css
  src/pages/Main.tsx
  src/pages/Movies.tsx
  src/pages/Series.tsx
Labels: 🐛 Bug
