Repository engsal-bin/FlickClick, pull requests merged in 2025-04, with the labels that each got.

#74 feat:실시간 기능 추가
  src/api/common.ts
  src/api/notification.ts
  src/components/common/Argument.tsx
  src/components/common/ArgumentReview.tsx
  src/components/common/Arguments.tsx
  src/components/common/InputTextarea.tsx
  src/components/common/Review.tsx
  src/components/common/Reviews.tsx
  src/components/mypage/Notify.tsx
  src/components/mypage/NotifyTab.tsx
  src/components/rootlayouts/Header.tsx
  src/type/mypageType.d.ts
Labels: ✨ Feat, 🔧 Fix, 🔨 Refactor

#76 design: 배너 디자인 및 링크연결
  src/assets/icon/github.svg
  src/components/common/Banner.tsx
Labels: 🎨 Design

#80 fix: 컨텐츠 리스트 스크롤 적용
  src/components/common/MediaList.tsx
  src/components/default-view/DefaultMoviesView.tsx
  src/components/default-view/DefaultSeriesView.tsx
Labels: 🔧 Fix

#82 fix: 컨텐츠리스트 제목 추가
  src/components/common/Contents.tsx
  src/components/common/MediaList.tsx
  src/components/default-view/DefaultMoviesView.tsx
  src/components/default-view/DefaultSeriesView.tsx
  src/pages/Main.tsx
  src/type/filterType.d.ts
Labels: 🔧 Fix

#88 Fix 콘텐츠리스트 스와이퍼적용 #84
  src/components/common/ArgorithmIP.tsx
  src/components/common/Contents.tsx
  src/components/common/MediaList.tsx
  src/components/mypage/ScrapEpisode.tsx
Labels: 🐛 Bug, 🔧 Fix

#90 fix:tsc build
  .github/workflows/deploy-netlify.yml
  public/_redirects
  src/api/common.ts
  src/components/common/MediaList.tsx
  src/components/mypage/MyOpinionContent.tsx
  src/components/mypage/Review.tsx
  src/pages/NewUpdate.tsx
Labels: 🔧 Fix

#100 Fix 콘텐츠리스트 스와이퍼적용 #84
  src/components/common/Contents.tsx
  src/components/common/MainThumbnail.tsx
  src/components/common/MediaList.tsx
Labels: ✨ Feat, 🔧 Fix

#109 bug: 방영연도 관련 버그 해결
  src/components/common/DetailIntroBox.tsx
  src/components/common/SeasonBox.tsx
Labels: 🐛 Bug

#110 방영연도 버그 해결
  src/components/common/DetailIntroBox.tsx
  src/components/common/SeasonBox.tsx
Labels: 🐛 Bug
